### ISSUE TITLE
Add documentation on the difference between S-, T-learners versus X-, F-, R-learners 

### ISSUE THREAD

**Issue by CrystalXuR** [som-shahlab/survlearners#98]
X-, F-, R-learners: the cate can only be estimated at one-time point, which is the "times" input for the model fitting 

S- and T-learners: the cate can be estimated at any time points as they provide entire curve

**Comment by erikcs** [comment]
We should all also go over and agree for a template what the (simple) doc should look like, e.g.

```R
#' The title: <Estimator name> 
#'
#' Short main paragraph: <Estimates tau(x) = E(T(1) > t0 |  X = x) - E(T(0) > t0 | X = x) where T(1) and ... using a "T-learner etc"
#'
#' Optional more details: <ideally not too much info here, can always refer to the paper>
#'
#' @param X The covariates
#' @param Y The outcome 
#' @param ... etc
#' @examples  < a very simple example fitting and predicting on X and X.test using predict>
#' @returns An object of type <.....>
#' @export
```

Same consistent setup for `predict.surv_`

```R
#' The title: <Predict with an "Estimator name"> 
#'
#' Estimate tau(x). Can optionally predict at new time point t0  etc..
#'
#' @param object  The trained model
#' @param newdata NULL The ....
#' @param t0 = NULL Optional new timepoint for ....
#' @param ...
#' @examples  <the exact same example used in <main estimator>
#' @returns A vector of predictions
#' @export
```

**Comment by CrystalXuR** [comment]
change F-learner of grf to "with"

**Comment by CrystalXuR** [comment]
<Estimates tau(x) = E(T(1) > t0 |  X = x) - E(T(0) > t0 | X = x) where T(1) etc etc. Using a censoring adjusted X-learner where the nuisance baselines risk is estimated with a balbal and the final cate with etc etc.

**Comment by CrystalXuR** [comment]
lasso for cate function on the x.trian is not out-of-bag, but grf is

**Comment by CrystalXuR** [comment]
chang times to t0
